### ISSUE TITLE
Lint error in typescript

### ISSUE THREAD

**Issue by nowrap** [sindresorhus/sort-keys#13]
Hello,
i am using sortKeys in a typescript project, but getting a lint error:
`sortKeys({a: 0, b: 1});`

Results in:
> This expression is not callable.
>   Type '{ default: <T extends { [key: string]: any; }>(object: T, opt
> ions?: Options | undefined) => T; }' has no call signatures.

The same result i am getting by using an object of type any:
```
    private generateParams(p: any, p1: string, p2: string): string {
        const sorted = sortKeys(p);
```
Regards
nowrap

**Comment by sindresorhus** [comment]
You are probably importing it incorrectly. Should be `import sortKeys = require('sort-keys');`.

**Comment by nowrap** [comment]
`import sortKeys from 'sort-keys';`
solved it. Before i had import * as
