### ISSUE TITLE
v5 breaks backwards compat

### ISSUE THREAD

**Issue by crobinson42** [sindresorhus/sort-keys#18]
![image](https://user-images.githubusercontent.com/5973579/116024786-cda22380-a603-11eb-8828-724f36808c19.png)

The package.json#module path should point to the esm bundle and a commonjs bundle should be built and package.json#main path should point to the commonjs build.

**Comment by sindresorhus** [comment]
Please read the release notes. I don't plan to provide a CommonJS build.
