### ISSUE TITLE
Objects inside arrays still need sorting

### ISSUE THREAD

**Issue by nyurik** [sindresorhus/sort-keys#5]
I had to write [my own sorter](https://github.com/kartotherian/babel/blob/master/test/debug-utils.js#L31), but would be great if you added this to your code - an ability to sort objects inside arrays, without changing the position in the arrays themselves.
```js
{
  b: 1
  a: [ { f: 10, e: 11 }, { h: 20, g: 21 }]
}
```
after sort:
```js
{
  a: [ { e: 11, f: 10 }, { g: 21, h: 20 }]
  b: 1
}
```

**Comment by sindresorhus** [comment]
Agreed. Pull request welcome :)
